name: "Lint commit messages"

# Run on every push to main (or your default branch) and on PRs
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  commit_lint:
    runs-on: ubuntu-latest

    steps:
      # 1. Fetch all history so we can diff commit ranges
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Set up Node.js (needed to run commitlint)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3. Install commitlint and the conventional-commits preset
      - name: Install Commitlint
        run: npm install @commitlint/cli @commitlint/config-conventional

      # 4. Run commitlint over the pushed or PR range
      - name: Lint commits
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            FROM_SHA="${{ github.event.pull_request.base.sha }}"
            TO_SHA="${{ github.event.pull_request.head.sha }}"
          else
            FROM_SHA="${{ github.event.before }}"
            TO_SHA="${{ github.sha }}"
          fi

          echo "Linting commits from $FROM_SHA to $TO_SHA"
          npx commitlint --from "$FROM_SHA" --to "$TO_SHA"
