name: "Lint PR title"

on:
  pull_request:

jobs:
  lint_pr_title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install commitlint
        run: npm install @commitlint/cli @commitlint/config-conventional

      - name: Lint PR title
        run: |
          # Grab the PR title
          echo "${{ github.event.pull_request.title }}" > pr_title.txt

          # Run commitlint in `--edit` mode against that single-line file
          npx commitlint --edit pr_title.txt --config commitlint.config.js
